# Generated by Django 6.0.6 on 2026-06-29 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL别名')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='分类图片')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('model_number', models.CharField(max_length=100, unique=True, verbose_name='型号编号')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL别名')),
                ('lift_type', models.CharField(choices=[('passenger', '乘客电梯'), ('freight', '载货电梯'), ('panoramic', '观光电梯'), ('hospital', '医用电梯'), ('escalator', '自动扶梯'), ('moving_walk', '自动人行道'), ('home', '家用电梯'), ('car', '汽车电梯')], max_length=30, verbose_name='电梯类型')),
                ('summary', models.CharField(blank=True, help_text='首页/列表页展示的短描述', max_length=300, verbose_name='简要卖点')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('technical_specs', models.JSONField(blank=True, default=dict, help_text='JSON格式存储详细技术参数', verbose_name='技术参数')),
                ('rated_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='额定速度(m/s)')),
                ('rated_capacity', models.IntegerField(blank=True, null=True, verbose_name='额定载重(kg)')),
                ('max_floors', models.IntegerField(blank=True, null=True, verbose_name='最大层站数')),
                ('max_passengers', models.IntegerField(blank=True, null=True, verbose_name='最大乘员数(人)')),
                ('energy_rating', models.CharField(blank=True, choices=[('A++', 'A++'), ('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=3, verbose_name='能效等级')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='基础价格(元)')),
                ('thumbnail', models.ImageField(blank=True, upload_to='products/thumbs/', verbose_name='缩略图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '电梯产品',
                'verbose_name_plural': '电梯产品',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='配件名称')),
                ('description', models.TextField(blank=True, verbose_name='配件描述')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格(元)')),
                ('is_optional', models.BooleanField(default=True, verbose_name='是否可选')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '可选配件',
                'verbose_name_plural': '可选配件',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='图片')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主图')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'ordering': ['sort_order'],
            },
        ),
    ]
