# Generated by Django 6.0.6 on 2026-06-29 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='供应商名称')),
                ('contact_person', models.CharField(max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, verbose_name='地址')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='税号')),
                ('bank_info', models.CharField(blank=True, max_length=300, verbose_name='银行账户信息')),
                ('rating', models.IntegerField(default=3, help_text='1-5星', verbose_name='评级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU编码')),
                ('name', models.CharField(max_length=200, verbose_name='物料名称')),
                ('category', models.CharField(choices=[('elevator', '电梯成品'), ('accessory', '配件'), ('part', '零部件'), ('consumable', '耗材')], default='elevator', max_length=50, verbose_name='物料分类')),
                ('unit', models.CharField(default='台', help_text='如：台、个、套、米', max_length=20, verbose_name='单位')),
                ('quantity', models.IntegerField(default=0, verbose_name='当前库存数量')),
                ('min_quantity', models.IntegerField(default=0, help_text='低于此数量触发预警', verbose_name='最低库存量')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成本单价(元)')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='销售单价(元)')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='库位')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '库存条目',
                'verbose_name_plural': '库存条目',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='采购单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('approved', '已审批'), ('ordered', '已下单'), ('partial', '部分到货'), ('received', '已入库'), ('cancelled', '已取消')], default='draft', max_length=30, verbose_name='状态')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='采购日期')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='预计到货日期')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='实际到货日期')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='采购合计(元)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='税额(元)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额(元)')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='inventory.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '采购订单',
                'verbose_name_plural': '采购订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='描述')),
                ('quantity', models.IntegerField(default=1, verbose_name='采购数量')),
                ('received_quantity', models.IntegerField(default=0, verbose_name='已收货数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价(元)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='小计(元)')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem', verbose_name='物料')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder', verbose_name='采购单')),
            ],
            options={
                'verbose_name': '采购明细',
                'verbose_name_plural': '采购明细',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase_in', '采购入库'), ('sale_out', '销售出库'), ('return_in', '退货入库'), ('return_out', '退供应商'), ('transfer', '移库'), ('adjustment', '盘点调整'), ('scrap', '报废')], max_length=30, verbose_name='操作类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('quantity_before', models.IntegerField(default=0, verbose_name='操作前数量')),
                ('quantity_after', models.IntegerField(default=0, verbose_name='操作后数量')),
                ('reference_number', models.CharField(blank=True, help_text='关联的采购单号/订单号等', max_length=100, verbose_name='关联单号')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem', verbose_name='物料')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to=settings.AUTH_USER_MODEL, verbose_name='仓库管理员')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.warehouse', verbose_name='所在仓库'),
        ),
    ]
